FROM alpine:3.19.1

RUN apk update && apk upgrade
RUN apk add 'python3<3.12'
RUN apk add 'gcc~=13.2.1_git20231014-r0' 'musl-dev==1.2.4_git20230717-r4' 'gmp-dev==6.3.0-r0' 'libseccomp-dev==2.5.5-r0' 'libseccomp==2.5.5-r0'
